ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "pricePinnedLeft" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerEnabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerPosition" TEXT NOT NULL DEFAULT 'BOTTOM';

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerShowClock" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerDataSource" TEXT NOT NULL DEFAULT 'CUSTOM';

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerCustomText" TEXT;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerApiUrl" TEXT;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerRefreshSec" INTEGER NOT NULL DEFAULT 180;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerBackgroundColor" TEXT NOT NULL DEFAULT '#111827';

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerTextColor" TEXT NOT NULL DEFAULT '#ffffff';
