ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "offerWindowBackgroundColor" TEXT NOT NULL DEFAULT '#f97316';

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "offerWindowTextColor" TEXT NOT NULL DEFAULT '#ffffff';

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "offerWindowOpacity" INTEGER NOT NULL DEFAULT 28;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerFontSize" INTEGER NOT NULL DEFAULT 14;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerInsetPx" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ScreenSetting"
ADD COLUMN IF NOT EXISTS "tickerOffsetPx" INTEGER NOT NULL DEFAULT 0;
