ALTER TABLE "Chain"
ADD COLUMN IF NOT EXISTS "payoutAccountHolder" TEXT;

ALTER TABLE "Chain"
ADD COLUMN IF NOT EXISTS "payoutBankName" TEXT;

ALTER TABLE "Chain"
ADD COLUMN IF NOT EXISTS "payoutIban" TEXT;

ALTER TABLE "Chain"
ADD COLUMN IF NOT EXISTS "payoutBic" TEXT;

ALTER TABLE "Chain"
ADD COLUMN IF NOT EXISTS "payoutEmail" TEXT;

ALTER TABLE "Chain"
ADD COLUMN IF NOT EXISTS "payoutReference" TEXT;
