-- AlterTable
ALTER TABLE "ScreenSetting"
ADD COLUMN "fontFamily" TEXT NOT NULL DEFAULT 'Poppins, sans-serif',
ADD COLUMN "productFontSize" INTEGER NOT NULL DEFAULT 34,
ADD COLUMN "ingredientFontSize" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN "categoryFontSize" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN "priceFontSize" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "cardPadding" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "cardBackgroundOpacity" INTEGER NOT NULL DEFAULT 35,
ADD COLUMN "cardBorderOpacity" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "defaultColumnCount" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN "showCategoryOnCard" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "categoryUppercase" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "priceDisplayMode" TEXT NOT NULL DEFAULT 'EUR_SUFFIX',
ADD COLUMN "logoUrl" TEXT,
ADD COLUMN "logoSize" INTEGER NOT NULL DEFAULT 72;

-- AlterTable
ALTER TABLE "ScreenDevice"
ADD COLUMN "columnCountOverride" INTEGER;
